language: node_js
sudo: false
node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - ./get_version.sh

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  repo: aria-music/aria-music.github.io
  target_branch: master
  keep_history: true
  local_dir: public
  fqdn: gaiji.pro
  github_token: $GITHUB_TOKEN
  committer_from_gh: true
  on:
    branch: master
