language: node_js
sudo: false
node_js:
  - node

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
