language: node_js
node_js:
  - node

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
