language: node_js
sudo: false
node_js:
  - node

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  repo: aria-music/aria-music.github.io
  target_branch: master
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
